export const WITCHES_CONTRACT_NAME = "CryptoCoven";
export const CONTRACT_NAMES = [
  WITCHES_CONTRACT_NAME,
];

export const WITCHES = {
  COMMUNITY_SALE_PRICE_ETH: "0.05",
  PUBLIC_SALE_PRICE_ETH: "0.07",
  MAX_WITCHES_MINTED: 9999,

  MAX_WITCHES: 9999,
  MAX_COMMUNITY_SALE_WITCHES: 3333,
  MAX_GIFTED_WITCHES: 250,
};
